query infrastruture($Org: [String], $TotalCount: Int, $Severity: [String]) {
  devices(
    search: {
      and: [
        { organization: { has: { company: { in: $Org } } } }
        { event: { has: { severity: { in: $Severity } } } }
      ]
    }
    first: $TotalCount
  ) {
    edges {
      node {
        organization {
          company
        }
        id
        ip
        name
        deviceClass {
          id
          logicalName
          class
          description
          deviceCategory {
            name
          }
        }
        asset {
          location
          make
        }
        events(search: { severity: { in: $Severity } }) {
          edges {
            node {
              message
              severity
              dateLast
            }
          }
        }
      }
    }
    pageInfo {
      matchCount
    }
  }
}
